WIN_WIDTH = 896
BUTTON_MARGINS = 8
WIN_HEIGHT = 896
INTERACT_RANGE = 128
TEXT_GAP = 20
CRIT_CHANCE = 6
SPRITE_SIZE = 128
WALL_SIZE = 96
DECO_SIZE = 96
TREE_SIZE = 128

# framerate de las animaciones idle (frames por segundo)
ANIM_FPS = 6

# posicionamiento del libro (Document)
DOC_MARGIN_X = 80
DOC_MARGIN_TOP = 80
DOC_MARGIN_BOTTOM = 240
DOC_PADDING = 36
DOC_LINE_GAP = 28
DOC_TITLE_GAP = 22
